authorName: default
experimentName: example_mnist_remote
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: remote
#search space file
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false  # true -> no searchSpacePath
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
#  codeDir: .
#  worker:
#    replicas: 1
#    command: python3 mnist.py
#    gpuNum: 0
#    cpuNum: 1
#    memoryMB: 8196
#    image: msranni/nni:latest
#  ps:
#    replicas: 1
#    command: python3 mnist.py
#    gpuNum: 0
#    cpuNum: 1
#    memoryMB: 8196
#    image: msranni/nni:latest
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
#machineList can be empty if the platform is local
machineList:
  - ip: x.x.x.x
    port: 22
    username: xxxx
    sshKeyPath: ~/.ssh/id_rsa
    passphrase: "xxxx"
  - ip: x.x.x.x
    port: 22
    username: xxxx
    sshKeyPath: ~/.ssh/id_rsa
    passphrase: "xxxx"

