apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
 namespace: default
 labels:
   controller-tools.k8s.io: "1.0"
 name: custom-lenet-tf3
spec:
 objective:
   type: maximize
   goal: 0.99
   objectiveMetricName: Validation-accuracy
   additionalMetricNames:
     - Train-accuracy
 algorithm:
   algorithmName: random
 parallelTrialCount: 3
 maxTrialCount: 6
 maxFailedTrialCount: 3
 parameters:
   - name: --learning_rate
     parameterType: double
     feasibleSpace:
       min: "0.01"
       max: "0.2"
   - name: --dropout
     parameterType: double
     feasibleSpace:
       min: "0.1"
       max: "0.5"
 trialTemplate:
   goTemplate:
       rawTemplate: |-
         apiVersion: batch/v1
         kind: Job
         metadata:
           name: {{.Trial}}
           namespace: {{.NameSpace}}
         spec:
           template:
             spec:
               containers:
               - name: {{.Trial}}
                 image: docker.io/soochem/custom-lenet-tf:0.0.1
                 command:
                 - "python3"
                 - "/app/task.py"
                 {{- with .HyperParameters}}
                 {{- range .}}
                 - "{{.Name}}={{.Value}}"
                 {{- end}}
                 {{- end}}
               restartPolicy: Never
