# 4 NVIDIA GPUs installed at local and tensorflow with GPU support.
# The demo enables 4 concurrent trail jobs and each trail job uses 1 GPU

authorName: default
experimentName: example_mnist_remote
# how many trials could be concurrently running
trialConcurrency: 4
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: remote
# search space file
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: true
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python main.py
  codeDir: ~/nni/examples/trials/mnist-annotation
  gpuNum: 1