authorName: default
experimentName: example_mnist_remote
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: remote
# search space file
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: true
tuner:
#  #choice: TPE, Random, Anneal, Evolution, BatchTuner
#  #SMAC (SMAC should be installed through nnictl)
#  builtinTunerName: TPE
#  classArgs:
#    #choice: maximize, minimize
#    optimize_mode: maximize
trial:
  command: python3 main.py
  codeDir: .
  gpuNum: 0
#machineList can be empty if the platform is local
machineList:
  - ip: 10.1.1.1
    username: bob
    passwd: bob123
    #port can be skip if using default ssh port 22
    #port: 22
  - ip: 10.1.1.2
    username: bob
    passwd: bob123
  - ip: 10.1.1.3
    username: bob
    passwd: bob123